name: Update All-Time Commit Count Badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2

      - name: Authenticate GH CLI
        run: gh auth setup-git

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Calculate total commits
        env:
          USER: ${{ github.repository_owner }}
        run: |
          TOTAL=0
          # List all repos for the user
          for repo in $(gh repo list $USER --limit 1000 --json name -q '.[].name'); do
            # Sum your commits in each repo
            COUNT=$(gh api repos/$USER/$repo/stats/contributors \
              | jq --arg USER "$USER" -r '.[] | select(.author.login == $USER) | .total // 0')
            TOTAL=$((TOTAL + COUNT))
          done

          # Create a Shields.io JSON endpoint spec
          jq -n --arg total "$TOTAL" \
            '{schemaVersion:1,label:"all-time commits",message:$total,color:"blue"}' \
            > commit-count.json

      - name: Commit and Push badge data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add commit-count.json
          git commit -m "chore: update all-time commit count" || echo "No changes"
          git push
